AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  うにの遊び場

  シンプルなLambda関数とAPI Gatewayを使用したコンタクトフォーム

Globals:
  Function:
    Timeout: 3

Resources:
  ContactFormFunction:
    Type: AWS::Serverless::Function 
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.8
      CodeUri: contact_form/
      MemorySize: 128
      Policies:
        - AmazonSESFullAccess
        - AWSLambdaBasicExecutionRole
      Events:
        ContactApi:
          Type: Api 
          Properties:
            Path: /contact
            Method: post

Outputs:
  ContactFormApi:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/contact/"
